config/routes.rb
MyTicketee::Application.routes.draw do

  resources :dashboard

  get "dashboard/index"

  devise_for :users, :controllers => { :registrations => "registrations", :sessions => "sessions" } do
    get '/sign_in', :to => 'devise/sessions#new'

  end
  devise_scope :user do
     root :to => 'devise/registrations#new'
  end

  resources :projects do
    resources :tickets
  end

  

end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true
  has_many :tickets, dependent: :delete_all

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :project
  validates :description, presence: true,
            length: { minimum: 10 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @projects = Project.all
    @project = Project.new

  end

  def show
    @tickets = @project.tickets.all
    @ticket = @project.tickets.build
  end

  def new
    @project = Project.new

  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
  def set_project
    @project = Project.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The project you were looking" +
        " for could not be found."
    redirect_to projects_path
  end


  def project_params
      params.require(:project).permit(:name, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  protected

  def after_sign_up_path_for(resource)
    dashboard_index_path
  end


end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
    protected
    def after_sign_in_path_for(resource)
    dashboard_index_path
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  def index
    @tickets = @project.tickets.all
  end

  def show
    @ticket = @project.tickets.find(params[:id])
  end


  def new
    @ticket = @project.tickets.build
  end

  def edit
  end

  def create
    @ticket = @project.tickets.build(ticket_params)
    if @ticket.save
      flash[:notice] = "Ticket has been created."
      redirect_to project_path(@project)
    else
      flash[:alert] = "Ticket has not been created."
      render "new"
    end
  end

  def update
    if @ticket.update(ticket_params)
      flash[:notice] = "Ticket has been updated."
      redirect_to [@project, @ticket]
    else
      flash[:alert] = "Ticket has not been updated."
      render action: "edit"
    end
  end

  def destroy
    @ticket.destroy
    flash[:notice] = "Ticket has been deleted."
    redirect_to @project
  end

  private
    def set_project
      @project = Project.find(params[:project_id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
          " for could not be found."
      redirect_to projects_path
    end

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def ticket_params
      params.require(:ticket).permit(:title, :description, :project_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Ticketee").join(" - ")
      end
    end
  end

  def active_if_current(path)
      'active' if current_page?(path)
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/dashboard/index.html.erb
<div class="span9">
  <h1>
    Dashboard
  </h1>
  <div class="hero-unit">
    <h1>
      Welcome!
    </h1>
    <p>
      To get the most out of Akira start with our 3 minute tour.
    </p>
    <p>
      <a href="help.htm" class="btn btn-primary btn-large">Start Tour</a> <a class="btn btn-large">No Thanks</a>
    </p>
  </div>
  <div class="well summary">
    <ul>
      <li>
        <a href="#"><span class="count">3</span> Projects</a>
      </li>
      <li>
        <a href="#"><span class="count">27</span> Tasks</a>
      </li>
      <li>
        <a href="#"><span class="count">7</span> Messages</a>
      </li>
      <li class="last">
        <a href="#"><span class="count">5</span> Files</a>
      </li>
    </ul>
  </div>
  <h2>
    Recent Activity
  </h2>
  <table class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>
        Project
      </th>
      <th>
        Client
      </th>
      <th>
        Type
      </th>
      <th>
        Date
      </th>
      <th>
        View
      </th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>
        Nike.com Redesign
      </td>
      <td>
        Monsters Inc
      </td>
      <td>
        New Task
      </td>
      <td>
        4 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Nike.com Redesign
      </td>
      <td>
        Monsters Inc
      </td>
      <td>
        New Message
      </td>
      <td>
        5 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Nike.com Redesign
      </td>
      <td>
        Monsters Inc
      </td>
      <td>
        New Project
      </td>
      <td>
        5 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Twitter Server Consulting
      </td>
      <td>
        Bad Robot
      </td>
      <td>
        New Task
      </td>
      <td>
        6 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Childrens Book Illustration
      </td>
      <td>
        Evil Genius
      </td>
      <td>
        New Message
      </td>
      <td>
        9 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Twitter Server Consulting
      </td>
      <td>
        Bad Robot
      </td>
      <td>
        New Task
      </td>
      <td>
        16 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Twitter Server Consulting
      </td>
      <td>
        Bad Robot
      </td>
      <td>
        New Project
      </td>
      <td>
        16 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    <tr>
      <td>
        Twitter Server Proposal
      </td>
      <td>
        Bad Robot
      </td>
      <td>
        Completed Project
      </td>
      <td>
        20 days ago
      </td>
      <td>
        <a href="#" class="view-link">View</a>
      </td>
    </tr>
    </tbody>
  </table>
  <ul class="pager">
    <li class="next">
      <a href="activity.htm">More &rarr;</a>
    </li>
  </ul>
</div>
</div>
</div>
	

app/views/layouts/_flash.html.erb
<% if notice.present? %>
    <p class="notice alert alert-success " id="flash_notice"><%= notice %></p>
    <%= javascript_tag "setTimeout(function(){ $('#flash_notice').remove(); }, 5000);" %>
<% end %>
<% if alert.present? %>
    <p class="alert alert-danger" id="flash_errors" ><%= alert %></p>
    <%= javascript_tag "setTimeout(function(){ $('#flash_errors').remove();}, 5000);" %>
<% end %>
<% flash[:error] = flash[:errors] = flash[:notice] = nil %>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse"> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </a> <a class="brand" href="#">Akira</a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active">
            <% if user_signed_in?   %>
                <%= link_to "Dashboard", dashboard_index_path%>
            <%else%>
                <a href="#">Dashboard</a>
            <%end%>
          </li>
          <li>
            <a href="settings.html">Account Settings</a>
          </li>
          <li>
            <a href="help.html">Help</a>
          </li>
          <li class="dropdown">
            <a href="help.html" class="dropdown-toggle" data-toggle="dropdown">Tours <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <li>
                <a href="help.html">Introduction Tour</a>
              </li>
              <li>
                <a href="help.html">Project Organisation</a>
              </li>
              <li>
                <a href="help.html">Task Assignment</a>
              </li>
              <li>
                <a href="help.html">Access Permissions</a>
              </li>
              <li class="divider">
              </li>
              <li class="nav-header">
                Files
              </li>
              <li>
                <a href="help.html">How to upload multiple files</a>
              </li>
              <li>
                <a href="help.html">Using file version</a>
              </li>
            </ul>
          </li>
        </ul>
        <form class="navbar-search pull-left" action="">
          <input type="text" class="search-query span2" placeholder="Search" />
        </form>
        <ul class="nav pull-right">
            <% if user_signed_in?   %>
                <li>
                    <a href="#"><%= current_user.email%></a>
                </li>

                <li>
                    <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                </li>
            <% else %>
                <li>
                    <%= link_to "Sign in", new_user_session_path  %>
                </li>
             <% end %>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/_sidebar.html.erb
 <div class="span3">
  <div class="well" style="padding: 8px 0;">
    <ul class="nav nav-list">
      <li class="nav-header">
        Akira
      </li>
      <li class="active">

        <%= link_to dashboard_index_path do %>
            <i class="icon-white icon-home"></i>
            <%= t(:Dashboard).html_safe %>
        <% end %>
      </li>
      <li>
        <%= link_to projects_path do %>
            <i class="icon-folder-open"></i>
            <%= t(:Projects).html_safe %>
        <%end%>
      </li>
      <li>
        <a href="tasks.htm"><i class="icon-check"></i> Tasks</a>
      </li>
      <li>
        <a href="messages.htm"><i class="icon-envelope"></i> Messages</a>
      </li>
      <li>
        <a href="files.htm"><i class="icon-file"></i> Files</a>
      </li>
      <li>
        <a href="activity.htm"><i class="icon-list-alt"></i> Activity</a>
      </li>
      <li class="nav-header">
        Your Account
      </li>
      <li>
        <a href="profile.htm"><i class="icon-user"></i> Profile</a>
      </li>
      <li>
        <a href="settings.htm"><i class="icon-cog"></i> Settings</a>
      </li>
      <li class="divider">
      </li>
      <li>
        <a href="help.htm"><i class="icon-info-sign"></i> Help</a>
      </li>
      <li class="nav-header">
        Bonus Templates
      </li>
      <li>
        <a href="gallery.htm"><i class="icon-picture"></i> Gallery</a>
      </li>
      <li>
        <a href="blank.htm"><i class="icon-stop"></i> Blank Slate</a>
      </li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <% if content_for?(:title) %>
        <%= yield(:title) %>
    <% else %>
        Ticketee
    <% end %>
  </title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= render 'layouts/navigation' %>
  <%= render 'layouts/flash' %>

  <div class="row">
    <% if user_signed_in?   %>
        <%= render 'layouts/sidebar' %>
    <%end%>
    <%= yield %>
  </div>

</div>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
      <%= f.label :name, :class=>"control-label",:for=>"input01" %>
      <div class="controls">
        <%= f.text_field :name ,:class=>"input-xlarge" ,:id=>"input01"%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class=>"control-label",:for=>"input01" %>
      <div class="controls">
        <%= f.text_field :description ,:class=>"input-xlarge" ,:id=>"input01"%>
      </div>
    </div>
    <div class="form-actions">
        <button type="submit" class="btn btn-primary">Create</button>
    </div>

<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="span9">
  <h1>
    Projects
  </h1>
  <table class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>
        Name
      </th>
      <th>
        Description
      </th>
      <th>
        Client
      </th>
      <th>
        Tasks
      </th>
      <th>
        Messages
      </th>
      <th>
        Files
      </th>
      <th>
        Progress
      </th>
    </tr>
    </thead>
    <tbody>
    <% @projects.each do |project| %>
    <tr>
      <td>
      <%= link_to project.name,project_path(project) %>
      </td>
      <td>
        <%= project.description %>
      </td>
      <td>
        Monsters Inc
      </td>
      <td>
        <span class="badge">11</span>
      </td>
      <td>
        <span class="badge">2</span>
      </td>
      <td>
        <span class="badge">4</span>
      </td>
      <td>
        <div class="progress">
          <div class="bar" style="width: 60%;"></div>
        </div>
      </td>
    </tr>
    <%end%>
    </tbody>
  </table>
  <a class="toggle-link" href="#new-project" id="new_project_page"><i class="icon-plus"></i> New Project</a>
    <div id="new-project" class="form-horizontal hidden">
      <%= render :partial => "projects/form"%>
    </div>

</div>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<div class="span9">
  <h1>
    Project <%= @project.name%>
  </h1>
  <table class="table table-bordered table-striped">
    <thead>
    <tr>
      <th>
        Title
      </th>
      <th>
        Description
      </th>
       <th>
        Created date
      </th>
       <th>
        Progress
      </th>
    </tr>
    </thead>
    <tbody>
    <% @tickets.each do |ticket| %>
    <tr>
      <td>
        <%= ticket.title %>
      </td>
      <td>
        <%= ticket.description%>Monsters Inc
      </td>
      <td>
        <%= ticket.created_at%>
      </td>
      <td>
        <div class="progress">
          <div class="bar" style="width: 60%;"></div>
        </div>
      </td>
     </tr>
    <%end%>
  </tbody>
  </table>
  <a class="toggle-link" href="#new-project" id="new_project_page"><i class="icon-plus"></i> New Ticket</a>
  <div id="new-project" class="form-horizontal hidden">
    <%= render :partial => "tickets/form"%>
  </div>
</div>
                                              test

app/views/tickets/_form.html.erb
<%= form_for([@project, @ticket]) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="control-group">
      <%= f.label :title, :class=>"control-label",:for=>"input01" %>
      <div class="controls">
        <%= f.text_field :title ,:class=>"input-xlarge" ,:id=>"input01"%>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :description, :class=>"control-label",:for=>"input01" %>
      <div class="controls">
        <%= f.text_field :description ,:class=>"input-xlarge" ,:id=>"input01"%>
      </div>
    </div>
    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Create</button>
    </div>

 <% end %>

app/views/tickets/edit.html.erb
<h1>Editing ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', project_tickets_path(@ticket) %> |
<%= link_to 'Back', project_tickets_path %>

app/views/tickets/index.html.erb
<h1>Listing tickets</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Project</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.title %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.project %></td>
        <td><%= link_to 'Show', project_ticket_path(@project,ticket) %></td>
        <td><%= link_to 'Edit', edit_project_ticket_path(@project,ticket) %></td>
        <td><%= link_to 'Destroy',project_ticket_path(@project,ticket), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_project_ticket_path %>

app/views/tickets/new.html.erb
<h1>New ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', project_tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @ticket.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Project:</strong>
  <%= @ticket.project %>
</p>

<%= link_to 'Edit', edit_project_ticket_path(@project,@ticket) %> |
<%= link_to 'Back', project_tickets_path %>